=== hmcts/cpp-context-staging-dcs/stagingdcs-command-api/src/raml/json/schema/create-case-defendant-file-in-dcs-request.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://moj.gov.uk/cpp/stagingdcs/submit-dcs-case-record-request.json",
  "description": "Information required to create a case in staging DCS",
  "type": "object",
  "properties": {
    "caseId": {
      "description": "The identifiers for the prosecution case",
      "$ref": "http://moj.gov.uk/cpp/stagingdcs/courtsDefinitions.json#/definitions/uuid"
    },
    "caseUrn": {
      "description": "URN of the case",
      "type": "string"
    },
    "defendants": {
      "description": "List of defendants for the case",
      "type": "array",
      "items": {
        "$ref": "http://moj.gov.uk/cpp/stagingdcs/defendant.json"
      }
    },
    "prosecutionAuthority": {
      "type": "string"
    }
  },
  "required": [
    "caseId",
    "defendants",
    "prosecutionAuthority"
  ],
  "additionalProperties": false
}

=== hmcts/cpp-context-staging-dcs/stagingdcs-integration-test/src/test/resources/json/stagingdcs.submit-dcs-case-record.json
{
  "caseId": "CASE_ID",
  "caseUrn": "CASE_URN",
  "prosecutionAuthority": "CPS",
  "defendants": [
    {
      "id": "DEFENDANT_ID",
      "bailStatus": "REMAND",
      "interpreterInformation": "German",
      "hearings": [
        {
          "courtCentre": "Southwark",
          "hearingDate": "2025-01-21"
        }
      ],
      "defendantPerson": {
        "forename": "John",
        "surname": "SMITH",
        "dateOfBirth": "1970-02-03"
      },
      "offencesDetails": {
        "addedOffences": [
          {
            "offenceId": "36a5a426-3d87-45a9-b079-0830ed0229db"
          }
        ]
      }
    }
  ]
}

=== hmcts/cpp-context-staging-dcs/stagingdcs-integration-test/src/test/resources/json/stagingdcs.submit-dcs-case-record-for-organisation.json
{
  "caseId": "CASE_ID",
  "caseUrn": "CASE_URN",
  "prosecutionAuthority": "CPS",
  "defendants": [
    {
      "id": "DEFENDANT_ID",
      "interpreterLanguage": "German",
      "hearings": [
        {
          "courtCentre": "Southwark",
          "hearingDate": "2025-01-21"
        }
      ],
      "defendantOrganisation": {
        "name": "test ltd"
      },
      "offencesDetails": {
        "addedOffences": [
          {
            "offenceId": "36a5a426-3d87-45a9-b079-0830ed0229db"
          }
        ]
      }
    }
  ]
}

=== hmcts/cpp-context-staging-dcs/stagingdcs-command-api/src/raml/json/stagingdcs.submit-dcs-case-record.json
{
  "caseId": "d9fe4c51-1783-4fe4-a2b4-7c0e25905484",
  "caseUrn": "PRJTASK0016152",
  "prosecutionAuthority": "CPS",
  "defendants": [
    {
      "id": "d9fe4c51-1783-4fe4-a2b4-7c0e25905485",
      "bailStatus": "REMAND",
      "interpreterLanguage": "German",
      "hearings": [
        {
          "courtCentre": "Southwark",
          "hearingDate": "2025-01-21"
        }
      ],
      "defendantPerson": {
        "forename": "John",
        "middleName": "Theodore",
        "surname": "SMITH",
        "dateOfBirth": "1970-02-03"
      },
      "offencesDetails": {
        "addedOffences": [
          {
            "offenceId": "36a5a426-3d87-45a9-b079-0830ed0229db"
          }
        ],
        "removedOffences": [
          {
            "offenceId": "36a5a426-3d87-45a9-b079-0830ed0229db"
          }
        ]
      }
    }
  ]
}

=== hmcts/cpp-context-staging-dcs/stagingdcs-integration-test/src/test/resources/json/submit-dcs-case-record-multiple-defendants.json
{
  "caseId": "CASE_ID",
  "caseUrn": "CASE_URN",
  "prosecutionAuthority": "CPS",
  "defendants": [
    {
      "id": "DEFENDANT_ID1",
      "bailStatus": "REMAND",
      "interpreterLanguage": "German",
      "hearings": [
        {
          "courtCentre": "Southwark",
          "hearingDate": "2025-01-21"
        }
      ],
      "defendantPerson": {
        "forename": "John",
        "middleName": "Theodore",
        "surname": "SMITH",
        "dateOfBirth": "1970-02-03"
      },
      "offencesDetails": {
        "addedOffences": [
          {
            "offenceId": "26a5a426-3d87-45a9-b079-0830ed0229db"
          }
        ],
        "removedOffences": [
          {
            "offenceId": "36a5a426-3d87-45a9-b079-0830ed0229db"
          }
        ]
      }
    },
    {
      "id": "DEFENDANT_ID2",
      "bailStatus": "REMAND",
      "interpreterLanguage": "German",
      "hearings": [
        {
          "courtCentre": "Southwark",
          "hearingDate": "2025-01-21"
        }
      ],
      "defendantPerson": {
        "forename": "Johnq",
        "middleName": "Theodore",
        "surname": "SMITHq",
        "dateOfBirth": "1971-02-03"
      },
      "offencesDetails": {
        "addedOffences": [
          {
            "offenceId": "36a5a426-3d87-45a9-b079-0830ed0229db"
          }
        ]
      }
    }
  ]
}

=== hmcts/cpp-context-staging-dcs/stagingdcs-integration-test/src/test/resources/json/stagingdcs.submit-dcs-case-record-remove-qr.json
{
  "caseId": "CASE_ID",
  "caseUrn": "CASE_URN",
  "prosecutionAuthority": "CPS",
  "defendants": [
    {
      "id": "DEFENDANT_ID",
      "bailStatus": "REMAND",
      "interpreterInformation": "German",
      "hearings": [
        {
          "courtCentre": "Southwark",
          "hearingDate": "2025-01-21"
        }
      ],
      "defendantPerson": {
        "forename": "John",
        "middleName": "Theodore",
        "surname": "SMITH",
        "dateOfBirth": "1970-02-03"
      },
      "offencesDetails": {
        "removedOffences": [
          {
            "offenceId": "36a5a426-3d87-45a9-b079-0830ed0229db"
          }
        ]
      }
    }
  ]
}

=== hmcts/cpp-context-staging-dcs/stagingdcs-integration-test/src/test/resources/json/stagingdcs.submit-dcs-case-record-two-defendant.json
{
  "caseId": "CASE_ID",
  "caseUrn": "CASE_URN",
  "prosecutionAuthority": "CPS",
  "defendants": [
    {
      "id": "DEFENDANT_ID1",
      "bailStatus": "REMAND",
      "interpreterInformation": "German",
      "hearings": [
        {
          "courtCentre": "Southwark",
          "hearingDate": "2025-01-21"
        }
      ],
      "defendantPerson": {
        "forename": "John1",
        "surname": "SMITH1",
        "dateOfBirth": "1970-02-03"
      },
      "offencesDetails": {
        "addedOffences": [
          {
            "offenceId": "36a5a426-3d87-45a9-b079-0830ed0229db"
          }
        ]
      }
    },
    {
      "id": "DEFENDANT_ID2",
      "bailStatus": "REMAND",
      "interpreterInformation": "German",
      "hearings": [
        {
          "courtCentre": "Southwark",
          "hearingDate": "2025-01-22"
        }
      ],
      "defendantPerson": {
        "forename": "John2",
        "surname": "SMITH2",
        "dateOfBirth": "1971-02-03"
      },
      "offencesDetails": {
        "addedOffences": [
          {
            "offenceId": "16a5a426-3d87-45a9-b079-0830ed0229dc"
          }
        ]
      }
    }
  ]
}
